bysort sex_new: ttest q112age if singleton==1, by(lowbwt)
bysort sex_new: ttest q72hgt if singleton==1, by(lowbwt)
bysort sex_new: ttest q71wgt if singleton==1, by(lowbwt)
bysort sex_new: ttest bmi if singleton==1, by(lowbwt)
bysort sex_new: ttest hipcirc if singleton==1, by(lowbwt)
bysort sex_new: ttest waistcirc2 if singleton==1, by(lowbwt)
bysort sex_new: ttest waist_hip if singleton==1, by(lowbwt)
bysort sex_new: ttest mn23sbp if singleton==1, by(lowbwt)
bysort sex_new: ttest mn23dbp if singleton==1, by(lowbwt)
bysort sex_new: ttest q111glu if singleton==1, by(lowbwt)
bysort sex_new: ttest q115chol if singleton==1, by(lowbwt)
bysort sex_new: ttest q116fat if singleton==1, by(lowbwt)
bysort sex_new: ttest q1117cre if singleton==1, by(lowbwt)
bysort sex_new: ttest q1124alb if singleton==1, by(lowbwt)
bysort sex_new: ttest gfr_ckd_epi if singleton==1, by(lowbwt)
ttest hipcirc if singleton==1, by(lowbwt)
ttest waistcirc2 if singleton==1, by(lowbwt)
ttest waist_hip if singleton==1, by(lowbwt)
bysort sex_new: ranksum q112age if singleton==1, by(lowbwt)
bysort sex_new: ranksum q72hgt if singleton==1, by(lowbwt)
bysort sex_new: ranksum q71wgt if singleton==1, by(lowbwt)
bysort sex_new: ranksum bmi if singleton==1, by(lowbwt)
bysort sex_new: ranksum hipcirc if singleton==1, by(lowbwt)
bysort sex_new: ranksum waistcirc2 if singleton==1, by(lowbwt)
bysort sex_new: ranksum waist_hip if singleton==1, by(lowbwt)
bysort sex_new: ranksum mn23sbp if singleton==1, by(lowbwt)
bysort sex_new: ranksum mn23dbp if singleton==1, by(lowbwt)
bysort sex_new: ranksum q111glu if singleton==1, by(lowbwt)
bysort sex_new: ranksum q115chol if singleton==1, by(lowbwt)
bysort sex_new: ranksum q116fat if singleton==1, by(lowbwt)
bysort sex_new: ranksum q1117cre if singleton==1, by(lowbwt)
bysort sex_new: ranksum q1124alb if singleton==1, by(lowbwt)
bysort sex_new: ranksum gfr_ckd_epi if singleton==1, by(lowbwt)
